# Tensors 

### Tensors are like ndarrays in numpy 

### Examples 

In [8]:
# import libraries
from __future__ import print_function
import numpy as np 
import torch 

#### <font color='red'>Create ndarray in numpy</font> 

In [6]:
x_np = np.array([2.0,3.3])
print(x_np)
print(type(x_np))

[2.  3.3]
<class 'numpy.ndarray'>


#### Create tensors in pytorch 

In [9]:
x_to = torch.tensor([2.0,3.3])
print(x_to)
print(type(x_to))

tensor([2.0000, 3.3000])
<class 'torch.Tensor'>


#### Similarly everyone can create zeros, ones or random  arrays(tensors) with torch 

In [12]:
# tensor with 2 dimensions (2*3) zero values
x_zeros = torch.zeros(2,3)
# x_z = np.zeros (2,3) # numpy based zeros ndarray 

# tensor with 2 dimension (2*3) ones value
x_ones = torch.ones(2,3)
# x_ones = np.ones(2,3) # numpy based ones ndarray

#tensor with 2 dimension (2*3) random values
x_rands = torch.rand(2,3)
# x_rands = np.rand(2,3)

#print corresponding tensors

print('Zeros tensor:')
print(x_zeros)

print('Ones tensor:')
print(x_ones)

print('Random tensor:')
print(x_rands)

Zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random tensor:
tensor([[0.7964, 0.3238, 0.7038],
        [0.4145, 0.6777, 0.6585]])


### Access to a tensor values is similar to numpy 

In [16]:
x_r = torch.rand(3,4)
row2 = x_r[1,:] # get the second row in x_r
col3 = x_r[:,2] # get the third column in x_r 
print('Whole random matrix:\n',x_r)
print('\nSecond row:\n',row2)
print('\nThird column:\n',col3)

# Same operation in numpy 
#x_r = np.rand(3,4)
#row2 = x_r[1,:] # get the second row in x_r
#col3 = x_r[:,2] # get the third column in x_r 

Whole random matrix:
 tensor([[0.6836, 0.4058, 0.9919, 0.1835],
        [0.1013, 0.3999, 0.1868, 0.7099],
        [0.8660, 0.4495, 0.9993, 0.3273]])

Second row:
 tensor([0.1013, 0.3999, 0.1868, 0.7099])

Third column:
 tensor([0.9919, 0.1868, 0.9993])


#### In order to <font color='red'> resize </font>a tesnsor use view function  Instead of reshape in numpy

In [17]:
x_rn = torch.randn(8,4)
x_rn2 = x_rn.view(32)
x_rn3 = x_rn.view(-1,16) # it generate a 2 * 16 tensor (-1 allows torch to compute another dim automatically)

print(x_rn.size(), x_rn2.size(), x_rn3.size())

torch.Size([8, 4]) torch.Size([32]) torch.Size([2, 16])


#### Example : Adding two tensors 

In [21]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
b = torch.randn(2,3)
c = a+b 
print(c)

#you can also do an inplace add operation like the following code
print(a.add(b))

tensor([[-0.3841,  3.8452,  3.2145],
        [ 2.1209,  3.4965,  5.4372]])
tensor([[-0.3841,  3.8452,  3.2145],
        [ 2.1209,  3.4965,  5.4372]])




## Some Other Useful Functions 

numel()  : Get <font color='red'>Number of Elements</font> for a tensor 

In [24]:
x1= torch.randint(1,10,(3,4)) # create a 3*4 random tensor with integer numbers among 1 to 10 
print('Tensor :\n',x1)
print('Number of elements:\n',torch.numel(x1))

Tensor :
 tensor([[6., 3., 5., 3.],
        [5., 2., 6., 1.],
        [3., 4., 6., 3.]])
Number of elements:
 12


In [25]:
x_np1 = np.array([[1,2],[3,4]])

x_to1 = torch.from_numpy(x_np1)

print('numpy array:\n',x_np1,' type:',type(x_np1))
print('\ntorch tensor:\n',x_to1,'  type:',type(x_to1))


numpy array:
 [[1 2]
 [3 4]]  type: <class 'numpy.ndarray'>

torch tensor:
 tensor([[1, 2],
        [3, 4]])   type: <class 'torch.Tensor'>


In [28]:
odr_nums = torch.arange(1,4, 0.5)
print(odr_nums)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000])


In [29]:
ls_nums = torch.linspace(2, 10 , 20) # return 20 numbers between 2 and 10 ( [2,10])
print(ls_nums)

tensor([ 2.0000,  2.4211,  2.8421,  3.2632,  3.6842,  4.1053,  4.5263,  4.9474,
         5.3684,  5.7895,  6.2105,  6.6316,  7.0526,  7.4737,  7.8947,  8.3158,
         8.7368,  9.1579,  9.5789, 10.0000])


In [30]:
a1 = torch.full((2,3),1.75)
print(a1)

tensor([[1.7500, 1.7500, 1.7500],
        [1.7500, 1.7500, 1.7500]])


In [32]:
x1 = torch.zeros(1,2,1,3)
x2 = torch.squeeze(x1)
print('orginal tensor size:',x1.size(), '  squeezed tensor size:' , x2.size())

orginal tensor size: torch.Size([1, 2, 1, 3])   squeezed tensor size: torch.Size([2, 3])


In [34]:
x3 = torch.tensor([[1,2,3],[4,5,6]])
tr_x3 = torch.t(x3)

print('original tensor:\n',x3)
print('transposed tensor:\n',tr_x3)

original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
transposed tensor:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
